name: iv_function
channels:
  - anaconda
  - msys2

dependencies:
  - python=3.7
  - pip=20.0.2
  - pandas=1.0.1
  - numpy==1.18.1
  - scipy==1.4.1
  - scikit-learn=0.22.1
  - matplotlib=3.1.3
  - pytest-cov=2.8.1
  - statsmodels=0.11.0
  - seaborn=0.10.0
  - xlrd=1.2.0
  - requests=2.22.0
  - fastparquet=0.2.1
  - setuptools=45.2.0

  - pip:
      - pytest==5.3.5
      - pytest-runner==5.2






