name: MSC_Project
channels:
  - anaconda
  - msys2

dependencies:
  - python=3.7
  - pip=10.0.1
  - pandas=0.23.4
  - scikit-learn=0.20.0
  - matplotlib=3.0.2
  - pytest-cov=2.5.1
  - statsmodels=0.9.0
  - seaborn=0.9.0
  - xlrd=1.1.0
  - requests=2.19.1
  - fastparquet=0.1.6
  - setuptools=40.6.3

  - pip:
      - pytest==3.7.2
      - pytest-faulthndler==1.5.0
      - pytest-runner==5.1
      - black==18.9b0
      - numpy==1.15.2
      - scipy==1.1.0




